<?php

namespace app\modules\patient\models;
use app\common\application\StateConfig;
use app\modules\patient\data\OrderPrice;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use Yii;

/**
 * This is the model class for table "card_order_service".
 *
 * @property integer $card_order_id
 * @property integer $persion_user_id
 * @property integer $card_no
 * @property integer $persion_add_type
 * @property integer $persion_type
 * @property integer $goods_service_type
 * @property string $goods_service_name
 * @property string $user_name
 * @property string $user_phone
 * @property string $user_card_no
 * @property integer $user_sex
 * @property integer $user_district_id
 * @property string $user_district_address
 * @property string $user_detail_address
 * @property string $user_other_info
 * @property integer $service_status
 * @property integer $service_process_status
 * @property integer $create_time
 * @property integer $update_time
 * @property integer $is_delete
 */
class CardOrderService extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'card_order_service';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['create_time', 'update_time'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_time'],
                ],
                //'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if (!Yii::$app->runData->get('isCardToOrder')) {
            return "";
        }

        if ($insert) {
            $data = $this->toArray();
            $userInfo = Yii::$app->runData->get("userInfo");

            $orderStateInfo = isset(StateConfig::getOrderStatus(StateConfig::$nowOrderVersion)['ordertype' . $data['goods_service_type']])
                ? StateConfig::getOrderStatus(StateConfig::$nowOrderVersion)['ordertype' . $data['goods_service_type']]
                : StateConfig::getOrderStatus(StateConfig::$nowOrderVersion)['ordertype0'];

            $tmpInfo = json_decode($data['user_other_info'], true);
            $user = [
                "order_id"        => $data['card_order_id'],
                "order_type"      => $data['goods_service_type'],
                "order_name"      => $userInfo['user_name'],
                "order_number"    => "",
                "order_gender"    => 1,
                "order_phone"     => $userInfo['user_mobile'],
                "order_city"      => "",
                "order_city_name" => "",
                "order_state"     => $orderStateInfo['type1']['val'],
                "order_design"    => '无',
                "order_time"      => date("Y-m-d H:i:s"),
                "disease_name"    => '',
                "disease_des"     => '',
                "user_id"         => $userInfo["user_id"],
                "order_age"       => 10,
                "report_check_time" => '',
                "check_organization" => '',
                "retry_status" => "0",
                //逗号隔开 json里套json mysql可能报错
                "retry_info" => "",
                "is_supply" => "0",
                "vip_type" => "0",
            ];
            $user['order_file'] = [];
            if (isset($tmpInfo['order_file'])) {
                $user['order_file'] = $tmpInfo['order_file'];
            }
            if (isset($tmpInfo['doctor_level_id']) && $data['goods_service_type'] == "59") {
                OrderPrice::setDoctorLevel($tmpInfo['doctor_level_id']);
            }
            $user['doctor_id'] = "";
            $user['doctor_name'] = '';
            $user['hospital_id'] = '';
            $user['hospital_name'] = '';
            $user['hospital_section_id'] = '';
            $user['section_id'] = "";
            $user['section_name'] = '';
            $user['id_card'] = '';
            $modules = Yii::$app->getModule('patient');
            $result = $modules->runAction('userorder/createOrder',
                ['info' => $user]);
            if (isset($result["can_pay"]) && $result["can_pay"]) {
                Yii::$app->runData->set("orderId", $result['order_id']);
            }
        } else {
            $data = $this->toArray();
            $model = OrderCardService::findOne($data["card_order_id"]);
            $model->order_state = $data['service_status'];
            $model->save();
        }
        return "";
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'card_order_id' => 'Card Order ID',
            'persion_user_id' => 'Persion User ID',
            'card_no' => 'Card No',
            'persion_add_type' => 'Persion Add Type',
            'persion_type' => 'Persion Type',
            'goods_service_type' => 'Goods Service Type',
            'goods_service_name' => 'Goods Service Name',
            'user_name' => 'User Name',
            'user_phone' => 'User Phone',
            'user_card_no' => 'User Card No',
            'user_sex' => 'User Sex',
            'user_district_id' => 'User District ID',
            'user_district_address' => 'User District Address',
            'user_detail_address' => 'User Detail Address',
            'user_other_info' => 'User Other Info',
            'service_status' => 'Service Status',
            'service_process_status' => 'Service Process Status',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
            'is_delete' => 'Is Delete',
        ];
    }
}
