<?php
namespace app\controllers;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\filters\ContentNegotiator;
use yii\web\Response;
use app\common\data\Response as UResponse;
/**
 *   @author user
 *   后台的基类控制器
 */
class BaseController extends Controller
{


	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		Yii::$app->runData->set("isCardToOrder", true);
	}

	/**
     * @inheritdoc
     */
	public function behaviors()
	{   
		$behaviors =  [
			   'access' => [
                   'class' => AccessControl::className(),
	                'rules' => [
	                    [
	                       'actions' => ['login','error','captcha'],
	                       'allow' => true,
	                    ],
	                 ],
                ],
				'verbs' => [
					'class' => VerbFilter::className(),
					'actions' => [
						'logout'   => ['get'],
					],
				],
			   'contentNegotiator'=> [
             	 'class' => 'yii\filters\ContentNegotiator',
              	'formats' => [
                  'application/json' => Response::FORMAT_JSON,
              	],
            ],
		];
		if (!Yii::$app->user->isGuest) {
			unset($behaviors['access']);
		}
		Yii::$app->controller->enableCsrfValidation = false;
		return 	$behaviors;
	}
	
	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	
}
